main/urls.py
from django.contrib import admin
from django.urls import path, include
from socialnetwork import urls as social
from users import urls as users
from posts import urls as posts
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico/', RedirectView.as_view(
        url=staticfiles_storage.url('favicon.ico'))),
    path('', include(social)),
    path('', include(users)),
    path('', include(posts)),
]

from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/new/', views.NewPost.as_view(), name='posts-new'),
    path('posts/<int:pk>/', views.PostDetail.as_view(), name='posts-detail'),
    path('posts/<int:pk>/delete/', views.PostDelete.as_view(), name='posts-del'),
    path('posts/<int:pk>/update/', views.PostUpdate.as_view(), name='posts-update')
]

socialnetwork/urls.py
from django.urls import path, include
from . import views

app_name = 'social'

urlpatterns = [
    path('', views.Home.as_view(), name='social-home'),
    path('about/', views.About.as_view(), name='social-about'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='users-signup'),
    path('login/', views.Login.as_view(), name='users-login'),
    path('logout/', auth.LogoutView.as_view(), name='users-logout'),
    path('user/<str:username>/', views.UserPostList.as_view(), name='users-user'),
    path('profile/', views.profile, name='users-profile')
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.urls import reverse_lazy


user = get_user_model()


class Post(models.Model):
    author = models.ForeignKey(user, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.title} Posted by {self.author}"

    def get_absolute_url(self):
        return reverse_lazy('posts:posts-detail', kwargs={'pk': self.pk})

socialnetwork/models.py
from django.db import models

users/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from PIL import Image

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = CloudinaryField('image')

    def __str__(self):
        return f"{self.user.username} Profile"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from . import models

class CreateUser(UserCreationForm):

    class Meta():
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()


class UpdateUser(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ('username', 'email')


class UpdateProfile(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ['profile_pic']

posts/views.py
from django.views.generic import CreateView, DetailView, DeleteView, UpdateView
from . import models
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin


class NewPost(LoginRequiredMixin, CreateView):
    model = models.Post
    fields = ('title', 'content')
    template_name = 'posts/new.html'
    success_url = reverse_lazy('social:social-home')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDetail(DetailView):
    model = models.Post
    template_name = 'posts/post.html'
    context_object_name = 'post'


class PostDelete(UserPassesTestMixin, DeleteView):
    model = models.Post
    template_name = 'posts/del.html'
    success_url = reverse_lazy('social:social-home')

    def test_func(self):

        post = self.get_object()

        return self.request.user == post.author


class PostUpdate(UserPassesTestMixin, UpdateView):
    model = models.Post
    fields = ('title', 'content')
    template_name = 'posts/update.html'

    def test_func(self):

        post = self.get_object()

        return self.request.user == post.author

socialnetwork/views.py
from django.views.generic import TemplateView, ListView
from posts import models


class Home(ListView):
    model = models.Post
    template_name = 'social/index.html'
    context_object_name = 'post'
    ordering = ['-date']
    paginate_by = 4


class About(TemplateView):
    template_name = 'social/about.html'

users/views.py
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib.auth.views import LoginView
from . import forms
from . import models
from django.contrib.auth.models import User
from posts import models as post
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages


class SignUp(CreateView):
    form_class = forms.CreateUser
    success_url = reverse_lazy('users:users-login')
    template_name = 'users/signup.html'


class Login(LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True


class UserPostList(ListView):
    model = post.Post
    template_name = 'users/user.html'
    context_object_name = 'post'
    ordering = ['-date']
    paginate_by = 4

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return post.Post.objects.filter(author=user).order_by('-date')


def profile(request):

    if request.method == 'POST':
        profile_form = forms.UpdateProfile(
            request.POST, request.FILES, instance=request.user.profile)

        user_form = forms.UpdateUser(request.POST, instance=request.user)

        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()
            messages.success(request, f"Youre account has been updated!")
            return redirect('users:users-profile')

    else:
        profile_form = forms.UpdateProfile(instance=request.user.profile)

        user_form = forms.UpdateUser(instance=request.user)

    context = {
        'profile_form': profile_form,
        'user_form': user_form
    }

    return render(request, 'users/profile.html', context)

posts/templates/posts/del.html
{% extends 'social/base.html' %}

{% block title %}Delete Post{% endblock %}

{% block body2 %}

<br>
  <form method="post">
    <legend><h1>Delete Post</h1></legend>
    <hr>
      {% csrf_token %}
      <a class="btn btn-info" href="{% url 'posts:posts-detail' pk=post.pk %}">Cancel</a>
      <button type="submit" class="btn btn-danger">Delete</button>
  </form>
  <br>
{% endblock %}

posts/templates/posts/new.html
{% extends 'social/base.html' %}

{% block title %}New Post{% endblock %}

{% block new-link %}active{% endblock %}

{% block body2 %}

{% load crispy_forms_tags %}
<br>
  <form method="post">
    <legend><h1>New Post</h1></legend>
    <hr>
    <fieldset>
      {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-secondary form-control">New Post</button>
    </fieldset>
  </form>
  <br>
{% endblock %}

posts/templates/posts/post.html
{% extends 'social/base.html' %}

{% block title %}Post by {{ post.author }}{% endblock %}

{% block body2 %}
  <br>
  <div class="card">
    <div class="card-header">
        <p><img class="rounded-circle" height="25px;" width="25px;" src="{{ post.author.profile.profile_pic.url }}"><a href="#" style="text-decoration: none;">@{{ post.author }}</a> Posted {{ post.date|timesince }} ago</p>
     </div>
     <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.content|linebreaks }}</p>
        {% if post.author == user %}
          <a class="btn btn-danger" href="{% url 'posts:posts-del' pk=post.pk %}">Delete</a>
          <a class="btn btn-info" href="{% url 'posts:posts-update' pk=post.pk %}">Update</a>
        {% endif %}
    </div>
</div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'social/base.html' %}

{% block title %}Update Post{% endblock %}

{% block body2 %}

{% load crispy_forms_tags %}
<br>
  <form method="post">
    <legend><h1>Update Post</h1></legend>
    <hr>
    <fieldset>
      {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-secondary form-control">Update Post</button>
    </fieldset>
  </form>
  <br>
{% endblock %}

socialnetwork/templates/social/about.html
{% extends 'social/base.html' %}

{% block title %}the2nerds{% endblock %}
{% block about %}active{% endblock %}

{% block body2 %}
<h1>About the2nerds</h1>
<br><br>
<div class="media">
  <div class="media-body">
    <h3 class="mt-0">About the creator</h3>
    <p>
        my name is Hussein i made this website as a blog for me, my freinds and everyone on the internet. im an intermediate programmer. i love open source, raspberry pi and inventing stuff.
        <script type='text/javascript' src='https://ko-fi.com/widgets/widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Support Me on Ko-fi', '#434B57', 'memesterhub');kofiwidget2.draw();</script>
    </p>
  </div>
</div>
<h1>Why the2nerds?</h1>
<p>you may be like why the2nerds? what does this name mean? me and my freind <a href="https://instagram.com/mahdiroyale2">mahdi</a> was talking about a website that we can post blogs on and stuff and i was like i will make that website so i named it the2nerds because he gave me the idea of this website. and im not creative so i didnt have any other name in my head.</p>
{% endblock %}

socialnetwork/templates/social/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'social/css/social.css' %}">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'social/css/bootstrap.min.css' %}">
    {% block optional %}{% endblock %}
  </head>

<body class="d-flex flex-column h-100">
<header>
    <nav class="navbar navbar-expand-lg fixed-top navbar-light">
      <div class="container">
      <a class="navbar-brand {% block about %}{% endblock %}" href="{% url 'social:social-about' %}"><img height="35px" width="35px" src="/media/code-solid.svg"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item {% block home-link %}{% endblock %}" active-color="black">
              <a class="nav-link" href="{% url 'social:social-home' %}"><b>Home</b></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item {% block profile-link %}{% endblock %}" active-color="black">
              <a class="nav-link" href="{% url 'users:users-profile' %}"><b>Profile</b></a>
            </li>
            <li class="nav-item {% block new-link %}{% endblock %}" active-color="black">
              <a class="nav-link" href="{% url 'posts:posts-new' %}"><b>New</b></a>
            </li>
              {% else %}
            <li class="nav-item {% block login-link %}{% endblock %}" active-color="black">
              <a class="nav-link" href="{% url 'users:users-login' %}"><b>Login</b></a>
            </li>
            {% endif %}
            <span class="nav-indicator"></span>
          </ul>
        </div>
    </div>
  </nav>
</header>

<main role="main" class="flex-shrink-0" style="margin-top: 90px;">
  <div class="container">
    <div class="row">
      {% block body %}{% endblock %}
    </div>
    <div class="container">
      {% block body2 %}{% endblock %}
    </div>
    <section class="text-center">
      {% block paginator %}
      {% endblock %}
    </section>
  </div>
</main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'social/js/jquery.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="{% static 'social/js/bootstrap.min.js' %}"></script>

    <script type="text/javascript">
          "use strict";

      var indicator = document.querySelector('.nav-indicator');
      var items = document.querySelectorAll('.nav-item');

      function handleIndicator(el) {
        items.forEach(function (item) {
          item.classList.remove('is-active');
          item.removeAttribute('style');
        });
        indicator.style.width = "".concat(el.offsetWidth, "px");
        indicator.style.left = "".concat(el.offsetLeft, "px");
        indicator.style.backgroundColor = el.getAttribute('active-color');
        el.classList.add('active');
        el.style.color = el.getAttribute('active-color');
      }

      items.forEach(function (item, index) {
        item.addEventListener('click', function (e) {
          handleIndicator(e.target);
        });
        item.classList.contains('active') && handleIndicator(item);
      });

    </script>
</body>

socialnetwork/templates/social/index.html
{% extends 'social/base.html' %}

{% block title %}the2nerds{% endblock %}
{% block home-link %}active{% endblock %}

{% load humanize %}

{% block body %}
  {% for p in post %}
  <br>
       <div class="col-md-6">
          <div class="card mb-4 shadow-sm">
            <div class="card-header">
              <p><img class="rounded-circle" height="25px;" src="{{ p.author.profile.profile_pic.url }}"> <a href="{% url 'users:users-user' username=p.author %}" style="text-decoration: none;">@{{ p.author }}</a></p>
            </div>
            <div class="card-body">
         <h5 class="card-title"><a href="{% url 'posts:posts-detail' pk=p.pk %}" style="text-decoration:none;">{{ p.title }}</a></h5>
        <p class="card-text">{{ p.content|linebreaks }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Posted {{ p.date|timesince }} ago</small>
              </div>
            </div>
          </div>
          </div>
{% endfor %}
{% endblock %}

{% block paginator %}
  {% if is_paginated %}

  <div style="align-content: center;">
    <div class="btn-group mr-2" style="align-items: center;" role="group" aria-label="First group">
      {% if page_obj.has_previous %}
        <a class="btn btn-secondary" href="?page={{ page_obj.previous_page_number }}"><<</a>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-secondary" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-secondary" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <a class="btn btn-secondary" href="?page={{ page_obj.next_page_number }}">>></a>
      {% endif %}
  </div>
  <br>
  <br>
</div>
  {% endif %}
{% endblock %}

users/templates/users/login.html
{% extends 'social/base.html' %}

{% block title %}Login Now!{% endblock %}

{% block login-link %}active{% endblock %}

{% block body2 %}

{% load crispy_forms_tags %}

<br>
  <form method="post">
    <legend class="border-bottom mb-4">Login <small style="font-size: 15px;" class="text-muted">Dont Have an account? <a style="color: #398fecd1;text-decoration: none;" href="{% url 'users:users-signup' %}">register</a></small></legend>
    <fieldset>
      {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-secondary form-control">Sign Up</button>
    </fieldset>
  </form>
  <br>
  <br>
{% endblock %}

users/templates/users/profile.html
{% extends 'social/base.html' %}

{% load crispy_forms_filters %}

{% block title %}Edit Profile{% endblock %}

{% block profile-link %}active{% endblock %}

{% block body2 %}
{% for msg in messages %}
  <div class="alert alert-{{ msg.tags }} alert-dismissible fade show" role="alert">
  {% if msg.tags == 'success' %}
    saved!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
  {% else %}
<div class="alert alert-{{ msg.tags }} alert-dismissible fade show" role="alert">
    error occured!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
  {% endif %}
{% endfor %}
<br>
<div class="card">
  <div class="card-body">
    <div class="content-section">
      <div class="media">
        <img height="120px;" width="120px;" class="rounded-circle account-img" src="{{ user.profile.profile_pic.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p style="margin-left: 10px;" class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
        <br>
    </div>
    <a href="{% url 'users:users-logout' %}" class="btn btn-secondary">Logout</a>
    <a class="ml-4 btn btn-success" href="{% url 'users:users-user' username=user.username %}">All Posts!</a>
  </div>
  </div>
  <br>
    <div class="card">
    <form class="card-body" method="post" enctype="multipart/form-data">
      {% csrf_token %}
          <fieldset class="form-group">
        <legend class="border-bottom mb-4">Update Profile</legend>
        {{ user_form|crispy }}
        {{ profile_form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-secondary form-control" type="submit">Update</button>
      </div>
    </form>
  </div>
  <br>
{% endblock %}

users/templates/users/signup.html
{% extends 'social/base.html' %}

{% block title %}Join Now!{% endblock %}

{% block body2 %}

{% load crispy_forms_tags %}
<br>
  <form method="post">
    <legend class="border-bottom mb-4">Join Now! <small style="font-size: 15px;" class="text-muted">Have an account? <a style="color: #398fecd1;text-decoration: none;" href="{% url 'users:users-login' %}">login</a></small></legend>
    <fieldset>
      {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-secondary form-control">Sign Up</button>
    </fieldset>
  </form>
  <br>
{% endblock %}

users/templates/users/user.html
{% extends 'social/base.html' %}

{% block title %}{{ username }}{% endblock %}

{% block body %}
{% for p in post %}
  <br>
       <div class="col-md-6">
          <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <p><img class="rounded-circle" height="25px;" width="25px;" src="{{ p.author.profile.profile_pic.url }}"> <a href="{% url 'users:users-user' username=p.author %}" style="text-decoration: none;">@{{ p.author }}</a></p>
            </div>
            <div class="card-body">
         <h5 class="card-title"><a href="{% url 'posts:posts-detail' pk=p.pk %}" style="text-decoration:none;">{{ p.title }}</a></h5>
        <p class="card-text">{{ p.content|linebreaks }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Posted {{ p.date|timesince }} ago</small>
              </div>
            </div>
          </div>
          </div>
{% endfor %}
{% endblock %}

{% block paginator %}
<br>
  {% if is_paginated %}
    <div class="btn-group mr-2" role="group" aria-label="First group">
      {% if page_obj.has_previous %}
        <a class="btn btn-secondary" href="?page={{ page_obj.previous_page_number }}"><<</a>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-secondary" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-secondary" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <a class="btn btn-secondary" href="?page={{ page_obj.next_page_number }}">>></a>
      {% endif %}
    {% endif %}
  </div>
  <br>
  <br>
{% endblock %}